### ISSUE TITLE
NRSur7dq4Remnant fit.all not working in version 1.1.1 or 1.1.3

### ISSUE THREAD

**Issue by avivajpeyi** [vijayvarma392/surfinBH#14]
## Installation steps:
`conda install -c conda-forge surfinbh`

## Code to reproduce error: 
```python
>>> import surfinBH
>>> BH_FIT = surfinBH.LoadFits('NRSur7dq4Remnant')
Loaded NRSur7dq4Remnant fit.
>>> print(f"surfinBH.__version__ = {surfinBH.__version__}")
surfinBH.__version__ = 1.1.1
>>> vals = BH_FIT.all(q=1, chiA=0.5, chiB=0.5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "//anaconda3/lib/python3.7/site-packages/surfinBH/surfinBH.py", line 309, in all
    return self._eval_wrapper('all', *args, **kwargs)
  File "//anaconda3/lib/python3.7/site-packages/surfinBH/_fit_evaluators/fit_7dq4.py", line 467, in _eval_wrapper
    x = np.concatenate(([q], chiA, chiB))
ValueError: all the input arrays must have same number of dimensions

```

## Attempt using the newer pip version:
```
pip uninstall surfinBH
pip install surfinBH
```

```python
>>> import surfinBH
>>> surfinBH.__version__
1.1.3
```

**Comment by avivajpeyi** [comment]
When I “fix” the above bug, ie `x = np.concatenate(([q], chiA, chiB))`
to `x = np.concatenate(([q], [chiA[0]], [chiB[0]]))`
I still get an error:
```
  BH_FIT.all(q=1, chiA=0.5, chiB=0.5)
```
Error:
```
  File "//anaconda3/lib/python3.7/site-packages/surfinBH/surfinBH.py", line 309, in all
    return self._eval_wrapper('all', *args, **kwargs)
  File "//anaconda3/lib/python3.7/site-packages/surfinBH/_fit_evaluators/fit_7dq4.py", line 494, in _eval_wrapper
    mf, mf_err = self._evaluate_fits(x, 'mf')
  File "//anaconda3/lib/python3.7/site-packages/surfinBH/surfinBH.py", line 139, in _evaluate_fits
    fit_params = self._get_fit_params(np.copy(x), fit_key)
  File "//anaconda3/lib/python3.7/site-packages/surfinBH/_fit_evaluators/fit_7dq4.py", line 247, in _get_fit_params
    q, chiAz, chiBz = x[0], x[3], x[6]
IndexError: index 3 is out of bounds for axis 0 with size 3

Process finished with exit code 1

```

**Comment by duetosymmetry** [comment]
For the 7d surrogate, spins should be vectors of length three, rather than only magnitudes.

**Comment by vijayvarma392** [comment]
@avivajpeyi, as Leo said, the inputs should be 3-vectors. This is explained in the documentation here: https://github.com/vijayvarma392/surfinBH/blob/master/examples/example_7dq4.ipynb. You can also see usage examples in the same notebook.

In your example, if you meant to use aligned-spins, you can use:
`vals = BH_FIT.all(q=1, chiA=[0, 0, 0.5], chiB=[0, 0, 0.5])`
